name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Download TightVNC
      run: |
        Write-Host "Downloading TightVNC installer..."
        Invoke-WebRequest -Uri https://www.tightvnc.com/download.php -OutFile TightVNCSetup.exe

    - name: Install TightVNC
      run: |
        Write-Host "Installing TightVNC silently..."
        Start-Process -FilePath "TightVNCSetup.exe" -ArgumentList "/S" -Wait

    - name: Start TightVNC Server
      run: |
        Write-Host "Starting TightVNC Server..."
        Start-Process "C:\Program Files\TightVNC\tvnserver.exe" -ArgumentList "-start"

    - name: Configure Firewall for TightVNC
      run: |
        Write-Host "Configuring Firewall for TightVNC..."
        Enable-NetFirewallRule -DisplayGroup "VNC"
    
    - name: Enable Remote Desktop
      run: |
        Write-Host "Enabling Remote Desktop..."
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Check TightVNC status
      run: |
        Write-Host "Checking TightVNC Server status..."
        Get-Service -Name tvnserver
