name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Install ngrok using Chocolatey
      run: |
        choco install ngrok -y

    - name: Authenticate ngrok
      run: |
        ngrok config add-authtoken 2Xf9VS1X9J8Cm0fDUD0WGUbGm4a_6YSNePWcAamMrBHixXB2X

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create batch file on desktop
      run: |
        $content = '@echo off
        setlocal
        echo Creating signal_file.txt... && echo. > C:\signal_file.txt && echo Signal file created successfully.

        pause
        endlocal'
        Set-Content -Path "$env:USERPROFILE\Desktop\create_signal_file.bat" -Value $content

    - name: Start ngrok tunnel and check for completion
      run: |
        Start-Process -NoNewWindow -FilePath ngrok -ArgumentList 'tcp 3389'
        
        $signalFile = "C:\signal_file.txt"
        $ngrokRunning = $true

        while ($ngrokRunning) {
          if (-not $ngrokRunning) { break }

          if (-not (Test-Path $signalFile)) {
            Start-Sleep -Seconds 60
            continue
          }

          $ngrokRunning = $false
        }

        Write-Output "Completion signal received."
