name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Install Node.js
      run: |
        # Download and install Node.js (necessary for localtunnel)
        Invoke-WebRequest -Uri "https://nodejs.org/dist/v16.16.0/node-v16.16.0-x64.msi" -OutFile "nodejs.msi"
        Start-Process msiexec.exe -ArgumentList '/i', 'nodejs.msi', '/quiet', '/norestart' -Wait

    - name: Install LocalTunnel
      run: |
        # Install LocalTunnel globally
        npm install -g localtunnel

    - name: Enable Remote Desktop
      run: |
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start LocalTunnel for RDP
      run: |
        # Expose the local RDP port (3389) via localtunnel
        lt --port 3389
        Write-Output "LocalTunnel started successfully"

    - name: Wait for Tunnel to Stabilize
      run: |
        # A simple wait time to ensure tunnel is active
        Start-Sleep -Seconds 60
        Write-Output "Waiting for tunnel to stabilize"
