name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: |
        Write-Host "Downloading ngrok..."
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Write-Host "Expanding ngrok archive..."
        Expand-Archive -Path ngrok.zip -DestinationPath .
        Write-Host "ngrok downloaded and extracted successfully."

    - name: Authenticate ngrok
      run: |
        Write-Host "Authenticating ngrok..."
        .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        Write-Host "ngrok authenticated successfully."
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Write-Host "Enabling Remote Desktop..."
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Write-Host "Remote Desktop connections enabled."
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Write-Host "Remote Desktop firewall rules enabled."
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Write-Host "User authentication for RDP set."
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Write-Host "User 'runneradmin' created with a password."

    - name: Create batch file on desktop
      run: |
        Write-Host "Creating batch file to generate signal file..."
        $content = '@echo off
        setlocal
        echo Creating signal_file.txt... && echo. > C:\signal_file.txt && echo Signal file created successfully.
        pause
        endlocal'
        Set-Content -Path "$env:USERPROFILE\Desktop\create_signal_file.bat" -Value $content
        Write-Host "Batch file 'create_signal_file.bat' created successfully."

    - name: Start ngrok tunnel and check for completion
      run: |
        Write-Host "Starting ngrok tunnel..."
        Start-Process -NoNewWindow -FilePath .\ngrok.exe -ArgumentList 'tcp 3389'
        Write-Host "Ngrok tunnel started for RDP on port 3389."
        
        $signalFile = "C:\signal_file.txt"
        $ngrokRunning = $true
        $retryCount = 0
        $maxRetries = 10
        while ($ngrokRunning) {
          Write-Host "Checking if signal file exists..."
          if (-not (Test-Path $signalFile)) {
            Write-Host "Signal file not found, waiting for 60 seconds..."
            Start-Sleep -Seconds 60
            $retryCount++
            if ($retryCount -ge $maxRetries) {
              Write-Host "Maximum retries reached. Signal file not found."
              break
            }
            continue
          }
          $ngrokRunning = $false
        }
        
        if ($ngrokRunning) {
          Write-Host "Ngrok tunnel setup failed due to signal file not being detected."
        } else {
          Write-Host "Signal file detected. Ngrok tunnel setup complete."
        }

        Write-Output "Completion signal received."
